### ISSUE TITLE
Corrections/updates to the README

### ISSUE THREAD

**Issue by spookylukey** [oscarmlage/django-cruds-adminlte#34]
Are you willing to take corrections and updates to the 'motivation' section of the README? If so, I'll submit some. e.g. in django.contrib.admin you can easily place fields alongside each other - see https://docs.djangoproject.com/en/1.11/ref/contrib/admin/#django.contrib.admin.ModelAdmin.fieldsets

There are also many 3rd party packages that extend the django.contrib.admin to provide the features you have here out-of-the box. 

This kind of thing will be helpful to people who want to assess whether to go with django-cruds-adminlte, or whether to stick with the stock Django admin.

**Comment by oscarmlage** [comment]
Yes, sure @spookylukey, first of all let me give you the thanks for the time you took to write the issue. The key is to give all the possible information to the end user.

I've read the `ModelAdmin.fieldsets` documentation but couldn't see how to put two fields side-by-side. If I've understood correctly you can group fields in a fieldset (collapsable/expandable and wider/narrower) but couldn't see how to put them 50% wider for example. Please let me know an example because it's so interesting.

Would be interesting too if you can provide here some other 3rdparty packages with the features `django-cruds-adminlte` is working on, because it can give us some ideas or, in best case, just use that packages.

**Comment by spookylukey** [comment]
It's under the `fields_options` docs:

    {
    'fields': (('first_name', 'last_name'), 'address', 'city', 'state'),
    }

Here, `first_name` and `last_name` will be side by side, `address` etc. will be on their own row.

**Comment by oscarmlage** [comment]
Cool, I've tested and it works, I'll update the README in the next commit. Please feel free to write down some other interesting resources.
