### ISSUE TITLE
Can not reproduce a example site 

### ISSUE THREAD

**Issue by luisza** [oscarmlage/django-cruds-adminlte#8]
Hi, 
I am trying to create a demo site based in your documentation but I haven't good results 
see https://github.com/luisza/django-cruds-adminlte/tree/demo   (demo branch in my fork).

I put a requirements.txt file to simplify installations of dependencies.
I get to work code as expected, but presentation is not good, widgets are not showing as expected.

Take a look to http://localhost:8000/testapp/customer/new/

**Comment by oscarmlage** [comment]
Hi @luisza.

I think I've reproduced the issue - my fault - the fact is that .gitignore has played a trick here. AdminLTE files are in lib/ directory, and some other assets are under dist/ dir (both ignored in .gitignore). 

A couple of comments about your _demo_:

- django-adminlte2 package is not needed (probably it shown an error there because of the .gitignore issue, some lib/ files were missing). You can delete it from requirements and from settings.py
- In forms.py you define `'text': CKEditorWidget(attrs={'lang': 'es'}),` and in fact the model field is called `information`, right? that's why ckeditor is not working.

**Comment by oscarmlage** [comment]
Just a comment more, now that I've tried your `demo` project, you need to add the following to your  `settings.py`:

    CRISPY_TEMPLATE_PACK = 'bootstrap3'
    IMAGE_CROPPING_JQUERY_URL = None

The first one renders better the forms (take a look to inputs and buttons), the second one prevents to get some conflicts with cropping widget and jquery (jquery is not needed to be included from the croppingwidget because we're including it in the adminlte template).

**Comment by luisza** [comment]
Hi, Thanks.
I uploaded new version of demo with this changes and login/logout views.  :)

**Comment by oscarmlage** [comment]
Great, I think we can merge your `demo` branch with the master one (dunno about de `db.sqlite3` file...) and add some documentation about the admin credentials and how to run/use the demo site. What do you think?

**Comment by luisza** [comment]
Yea, I would be nice, but I having problems saving time field (a format error) so first I need to check that and some errors that I saw.
